# Generated by Django 6.0.5 on 2026-05-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('reverse_score', models.BooleanField(default=False, verbose_name='Обратная шкала')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос диагностики',
                'verbose_name_plural': 'Вопросы диагностики',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('description', models.TextField(verbose_name='Инструкция')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('exercise_type', models.CharField(default='text', max_length=50, verbose_name='Тип')),
                ('timer_seconds', models.PositiveIntegerField(default=0, verbose_name='Таймер в секундах')),
                ('button_text', models.CharField(default='Далее', max_length=80, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['day__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок программы',
                'verbose_name_plural': 'Блоки программы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос/текст')),
                ('question_type', models.CharField(choices=[('text', 'Текстовое поле'), ('textarea', 'Большое текстовое поле'), ('select', 'Список'), ('multiselect', 'Множественный выбор'), ('scale', 'Шкала'), ('info', 'Информационный блок')], default='textarea', max_length=20, verbose_name='Тип вопроса')),
                ('options', models.TextField(blank=True, verbose_name='Варианты через точку с запятой')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('scale_min', models.IntegerField(default=1, verbose_name='Минимум шкалы')),
                ('scale_max', models.IntegerField(default=10, verbose_name='Максимум шкалы')),
                ('scale_default', models.IntegerField(default=5, verbose_name='Значение по умолчанию')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='emotional_app.exercise')),
            ],
            options={
                'verbose_name': 'Вопрос упражнения',
                'verbose_name_plural': 'Вопросы упражнений',
                'ordering': ['exercise__day__number', 'exercise__order', 'order'],
                'unique_together': {('exercise', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='День')),
                ('title', models.CharField(max_length=200, verbose_name='Название дня')),
                ('intro_text', models.TextField(blank=True, verbose_name='Пояснение дня')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='emotional_app.programblock')),
            ],
            options={
                'verbose_name': 'День программы',
                'verbose_name_plural': 'Дни программы',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='emotional_app.programday'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_or_email', models.CharField(max_length=150, verbose_name='Почта или телефон')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=14, verbose_name='День диагностики')),
                ('score', models.PositiveIntegerField(verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_app.diagnosticquestion')),
            ],
            options={
                'verbose_name': 'Ответ диагностики',
                'verbose_name_plural': 'Ответы диагностики',
                'unique_together': {('user', 'question', 'day_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('day', 'order')},
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Ответ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='emotional_app.exercisequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserDayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='emotional_app.programday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по дню',
                'verbose_name_plural': 'Прогресс по дням',
                'unique_together': {('user', 'day')},
            },
        ),
    ]
