# Generated by Django 6.0.5 on 2026-06-06 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotional_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDiagnosticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255)),
                ('criterion', models.CharField(choices=[('reappraisal', 'Когнитивная переоценка'), ('suppression', 'Эмоциональное подавление'), ('wellbeing', 'Субъективное благополучие'), ('stability', 'Эмоциональная стабильность'), ('reflection_awareness', 'Трудности рефлексии: осознание'), ('reflection_verbalization', 'Трудности рефлексии: вербализация'), ('reflection_tolerance', 'Трудности рефлексии: нетерпимость'), ('reflection_avoidance', 'Трудности рефлексии: избегание'), ('ecv', 'Ценность эмоционального контроля')], max_length=50)),
                ('text', models.TextField()),
                ('scale_min', models.IntegerField(default=1)),
                ('scale_max', models.IntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('reverse_score', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FinalDiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(default=dict)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalDiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotional_app.finaldiagnosticquestion')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
