# Generated by Django 6.0.5 on 2026-06-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotional_app', '0002_finaldiagnosticquestion_finaldiagnosticresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldiagnosticquestion',
            name='left_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finaldiagnosticquestion',
            name='method_code',
            field=models.CharField(choices=[('wellbeing', 'Методика диагностики субъективного благополучия'), ('erq', 'Опросник эмоциональной регуляции ERQ'), ('ecv', 'Ценности эмоционального контроля ECV'), ('srspm', 'Стиль саморегуляции поведения ССПМ-2020'), ('fivepfq', 'Пятифакторный опросник личности 5PFQ')], default='wellbeing', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaldiagnosticquestion',
            name='right_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finaldiagnosticquestion',
            name='criterion',
            field=models.CharField(choices=[('wellbeing', 'Субъективное благополучие'), ('erq_reappraisal', 'Когнитивная переоценка'), ('erq_suppression', 'Эмоциональное подавление'), ('ecv', 'Ценность эмоционального контроля'), ('srspm_total', 'Стиль саморегуляции поведения'), ('fivepfq_total', 'Пятифакторный опросник личности'), ('fivepfq_emotional_stability', 'Эмоциональная стабильность')], max_length=80),
        ),
    ]
